Static pages
langtonfavor/sample_app pull request #1
Opened 2021-11-08 12:58 UTC by langtonfavor

2021-11-09 08:52 UTC, JOlsen-Neslo requested changes

2021-11-09 08:52 UTC, JOlsen-Neslo commented on config/routes.rb
> +  root 'static_pages#home'
The root route must be first, all other must follow

2021-11-09 13:17 UTC, JOlsen-Neslo requested changes

2021-11-09 13:17 UTC, JOlsen-Neslo commented on config/routes.rb
> +  root             'static_pages#home'
The root route is still not at the beginning

2021-11-09 23:22 UTC, JOlsen-Neslo requested changes

2021-11-09 23:22 UTC, JOlsen-Neslo commented on config/routes.rb
> +  get 'static_pages/contact'
Why are both these here?

2021-11-10 12:10 UTC, JOlsen-Neslo approved these changes

2021-11-10 12:12 UTC, JOlsen-Neslo commented
Don't think I have permissions to merge

2021-11-10 12:13 UTC, langtonfavor commented
will  merge it

On Wed, Nov 10, 2021 at 2:12 PM Jordan Olsen ***@***.***>
wrote:

> Don't think I have permissions to merge
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/langtonfavor/sample_app/pull/1#issuecomment-965072628>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AFNJXKDDFXOOG6PRM26LH3DULJOS3ANCNFSM5HSTHOYQ>
> .
>

2021-11-10 12:21 UTC, merged